# Generated by Django 4.2.7 on 2023-11-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("kind", models.CharField(default="고추", max_length=100)),
                ("count", models.IntegerField(default=0)),
                ("price", models.IntegerField()),
                ("photo", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
