# Generated by Django 4.2.7 on 2023-11-16 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pest",
            fields=[
                ("pest_id", models.AutoField(primary_key=True, serialize=False)),
                ("problum", models.TextField(null=True)),
                ("photo", models.CharField(max_length=100, null=True)),
                ("solution", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm_id",
                    models.ForeignKey(
                        db_column="farm_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farms.farms",
                    ),
                ),
            ],
        ),
    ]
