# Generated by Django 4.2.7 on 2023-11-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_is_active_remove_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile",
        ),
    ]
