# Generated by Django 4.2.7 on 2023-11-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="review",
            name="product_id",
        ),
        migrations.AddField(
            model_name="review",
            name="product_name",
            field=models.CharField(default="유기농 홍고추", max_length=100),
            preserve_default=False,
        ),
    ]
