# Generated by Django 4.2.7 on 2023-11-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_review_photo_remove_review_product_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product",
            new_name="product_name",
        ),
    ]
