# Generated by Django 4.2.7 on 2023-11-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_rename_product_order_product_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="order",
            new_name="order_id",
        ),
        migrations.AddField(
            model_name="review",
            name="photo",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
