# Generated by Django 4.2.7 on 2023-11-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_rename_order_review_order_id_review_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="order_id",
            new_name="order",
        ),
    ]
