# Generated by Django 4.2.7 on 2023-11-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_rename_order_id_review_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="order",
            field=models.ForeignKey(
                db_column="order_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="order.order",
            ),
        ),
        migrations.RenameField(
            model_name="review",
            old_name="order",
            new_name="order_id",
        ),
    ]
