# Generated by Django 4.2.7 on 2023-11-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_review_order_rename_order_review_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="nickname",
        ),
        migrations.AddField(
            model_name="review",
            name="user_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
