# Generated by Django 4.2.7 on 2023-11-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_name"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product_id",
        ),
        migrations.AddField(
            model_name="cart",
            name="product_name",
            field=models.ForeignKey(
                db_column="product_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                to_field="name",
            ),
            preserve_default=False,
        ),
    ]
